
package gamingcafe;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Bill & Invoice Presentation Frame
 * Displays the complete invoice breakdown and provides PDF export functionality
 * 
 * @author Damsith Dewmina
 */
public class BillFrame extends javax.swing.JFrame {

    private String invoiceNo = "INV-000000";
    private String sessionId = "SES-000000";
    private String stationName = "Station 01";
    private String category = "PC";
    private String customerName = "Walk-in Customer";
    private String customerPhone = "-";
    private int durationMinutes = 60;
    private double hourlyRate = 150.00;
    private double subTotal = 150.00;
    private double discount = 0.00;
    private double netTotal = 150.00;
    private String staffName = "Admin";
    private String invoiceDateStr = "";

    public BillFrame() {
        initComponents();
        this.invoiceDateStr = new SimpleDateFormat("yyyy-MM-dd hh:mm a").format(new Date());
        updateBillDisplay();
    }

    public BillFrame(String invoiceNo, String sessionId, String stationName, String category,String customerName, String customerPhone, int durationMinutes,double hourlyRate, double subTotal, double discount, double netTotal, String staffName) {
        initComponents();
        this.invoiceNo = invoiceNo != null ? invoiceNo : "INV-" + (System.currentTimeMillis() % 1000000);
        this.sessionId = sessionId != null ? sessionId : "SES-000000";
        this.stationName = stationName != null ? stationName : "Station";
        this.category = category != null ? category : "PC";
        this.customerName = (customerName != null && !customerName.isEmpty()) ? customerName : "Walk-in Customer";
        this.customerPhone = (customerPhone != null && !customerPhone.isEmpty()) ? customerPhone : "-";
        this.durationMinutes = durationMinutes;
        this.hourlyRate = hourlyRate;
        this.subTotal = subTotal;
        this.discount = discount;
        this.netTotal = netTotal;
        this.staffName = (staffName != null && !staffName.isEmpty()) ? staffName : "System Staff";
        this.invoiceDateStr = new SimpleDateFormat("yyyy-MM-dd hh:mm a").format(new Date());

        updateBillDisplay();
    }

    /**
     * Update all UI labels with current invoice details
     */
    private void updateBillDisplay() {
        lblInvoiceNo.setText(this.invoiceNo);
        lblInvoiceDate.setText(this.invoiceDateStr);
        lblSessionId.setText(this.sessionId);
        lblStaffName.setText(this.staffName);

        lblCusName.setText(this.customerName);
        lblCusPhone.setText("Tel: " + this.customerPhone);

        lblStationName.setText(this.stationName);
        lblCategoryBadge.setText("CATEGORY: " + this.category.toUpperCase());

        int hrs = durationMinutes / 60;
        int mins = durationMinutes % 60;
        String durFormatted = String.format("%d mins (%02dh %02dm)", durationMinutes, hrs, mins);
        lblDurationVal.setText(durFormatted);

        lblRateVal.setText("Rs. " + String.format("%.2f", hourlyRate) + " / hr");
        lblSubTotalVal.setText("Rs. " + String.format("%.2f", subTotal));
        lblDiscountVal.setText("Rs. " + String.format("%.2f", discount));
        lblNetTotalVal.setText("Rs. " + String.format("%.2f", netTotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblCafeTitle = new javax.swing.JLabel();
        lblReceiptSubtitle = new javax.swing.JLabel();
        pnlInvoiceCard = new javax.swing.JPanel();
        lblInvNoTitle = new javax.swing.JLabel();
        lblInvoiceNo = new javax.swing.JLabel();
        lblDateTitle = new javax.swing.JLabel();
        lblInvoiceDate = new javax.swing.JLabel();
        lblSessionIdTitle = new javax.swing.JLabel();
        lblSessionId = new javax.swing.JLabel();
        lblStaffTitle = new javax.swing.JLabel();
        lblStaffName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCustomerTitle = new javax.swing.JLabel();
        lblCusName = new javax.swing.JLabel();
        lblCusPhone = new javax.swing.JLabel();
        lblStationTitle = new javax.swing.JLabel();
        lblStationName = new javax.swing.JLabel();
        lblCategoryBadge = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDurationL = new javax.swing.JLabel();
        lblDurationVal = new javax.swing.JLabel();
        lblRateL = new javax.swing.JLabel();
        lblRateVal = new javax.swing.JLabel();
        lblSubTotalL = new javax.swing.JLabel();
        lblSubTotalVal = new javax.swing.JLabel();
        lblDiscountL = new javax.swing.JLabel();
        lblDiscountVal = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlTotalBox = new javax.swing.JPanel();
        lblNetTotalL = new javax.swing.JLabel();
        lblNetTotalVal = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        btnPrintPdf = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Session Invoice & Bill Receipt");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(11, 19, 43));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(0, 51, 102));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCafeTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCafeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCafeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCafeTitle.setText("GAMING CAFE & LOUNGE");
        pnlHeader.add(lblCafeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 500, 24));

        lblReceiptSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReceiptSubtitle.setForeground(new java.awt.Color(0, 204, 255));
        lblReceiptSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceiptSubtitle.setText("OFFICIAL SESSION INVOICE & RECEIPT");
        pnlHeader.add(lblReceiptSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 500, 18));

        pnlMain.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        pnlInvoiceCard.setBackground(new java.awt.Color(16, 25, 45));
        pnlInvoiceCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 45, 74), 1, true));
        pnlInvoiceCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInvNoTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblInvNoTitle.setText("Invoice No:");
        pnlInvoiceCard.add(lblInvNoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 80, 20));

        lblInvoiceNo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblInvoiceNo.setForeground(new java.awt.Color(0, 204, 255));
        lblInvoiceNo.setText("INV-000000");
        pnlInvoiceCard.add(lblInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 15, 130, 20));

        lblDateTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblDateTitle.setText("Date:");
        pnlInvoiceCard.add(lblDateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 15, 45, 20));

        lblInvoiceDate.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoiceDate.setText("2026-09-27 16:30");
        pnlInvoiceCard.add(lblInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 15, 150, 20));

        lblSessionIdTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblSessionIdTitle.setText("Session ID:");
        pnlInvoiceCard.add(lblSessionIdTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        lblSessionId.setForeground(new java.awt.Color(255, 255, 255));
        lblSessionId.setText("SES-000000");
        pnlInvoiceCard.add(lblSessionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 130, 20));

        lblStaffTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblStaffTitle.setText("Staff:");
        pnlInvoiceCard.add(lblStaffTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 40, 45, 20));

        lblStaffName.setForeground(new java.awt.Color(255, 255, 255));
        lblStaffName.setText("System Staff");
        pnlInvoiceCard.add(lblStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 40, 150, 20));

        jSeparator1.setForeground(new java.awt.Color(31, 45, 74));
        pnlInvoiceCard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, 430, 10));

        lblCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCustomerTitle.setForeground(new java.awt.Color(0, 204, 255));
        lblCustomerTitle.setText("CUSTOMER DETAILS");
        pnlInvoiceCard.add(lblCustomerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 18));

        lblCusName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCusName.setForeground(new java.awt.Color(255, 255, 255));
        lblCusName.setText("Walk-in Customer");
        pnlInvoiceCard.add(lblCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 250, 20));

        lblCusPhone.setForeground(new java.awt.Color(148, 163, 184));
        lblCusPhone.setText("Tel: -");
        pnlInvoiceCard.add(lblCusPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 102, 160, 20));

        lblStationTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStationTitle.setForeground(new java.awt.Color(0, 204, 255));
        lblStationTitle.setText("GAMING STATION");
        pnlInvoiceCard.add(lblStationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 200, 18));

        lblStationName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStationName.setForeground(new java.awt.Color(255, 255, 255));
        lblStationName.setText("Station 01 [PC]");
        pnlInvoiceCard.add(lblStationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 154, 250, 20));

        lblCategoryBadge.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCategoryBadge.setForeground(new java.awt.Color(6, 214, 0));
        lblCategoryBadge.setText("CATEGORY: PC");
        pnlInvoiceCard.add(lblCategoryBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 154, 160, 20));

        jSeparator2.setForeground(new java.awt.Color(31, 45, 74));
        pnlInvoiceCard.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 184, 430, 10));

        lblDurationL.setForeground(new java.awt.Color(148, 163, 184));
        lblDurationL.setText("Total Duration:");
        pnlInvoiceCard.add(lblDurationL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 22));

        lblDurationVal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDurationVal.setForeground(new java.awt.Color(255, 255, 255));
        lblDurationVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDurationVal.setText("60 mins (01h 00m)");
        pnlInvoiceCard.add(lblDurationVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, 22));

        lblRateL.setForeground(new java.awt.Color(148, 163, 184));
        lblRateL.setText("Hourly Rate:");
        pnlInvoiceCard.add(lblRateL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 22));

        lblRateVal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRateVal.setForeground(new java.awt.Color(255, 209, 102));
        lblRateVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRateVal.setText("Rs. 150.00 / hr");
        pnlInvoiceCard.add(lblRateVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 200, 22));

        lblSubTotalL.setForeground(new java.awt.Color(148, 163, 184));
        lblSubTotalL.setText("Sub Total:");
        pnlInvoiceCard.add(lblSubTotalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 22));

        lblSubTotalVal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSubTotalVal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotalVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotalVal.setText("Rs. 150.00");
        pnlInvoiceCard.add(lblSubTotalVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, 22));

        lblDiscountL.setForeground(new java.awt.Color(148, 163, 184));
        lblDiscountL.setText("Discount:");
        pnlInvoiceCard.add(lblDiscountL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, 22));

        lblDiscountVal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDiscountVal.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscountVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscountVal.setText("Rs. 0.00");
        pnlInvoiceCard.add(lblDiscountVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 22));

        jSeparator3.setForeground(new java.awt.Color(31, 45, 74));
        pnlInvoiceCard.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 322, 430, 10));

        pnlTotalBox.setBackground(new java.awt.Color(7, 13, 31));
        pnlTotalBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 163), 1, true));
        pnlTotalBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNetTotalL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNetTotalL.setForeground(new java.awt.Color(255, 255, 255));
        lblNetTotalL.setText("NET TOTAL DUE:");
        pnlTotalBox.add(lblNetTotalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 150, 24));

        lblNetTotalVal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNetTotalVal.setForeground(new java.awt.Color(0, 255, 163));
        lblNetTotalVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNetTotalVal.setText("Rs. 150.00");
        pnlTotalBox.add(lblNetTotalVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 12, 240, 30));

        pnlInvoiceCard.add(pnlTotalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 430, 55));

        lblPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPaymentMethod.setForeground(new java.awt.Color(148, 163, 184));
        lblPaymentMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaymentMethod.setText("Payment Method: CASH  |  Status: PAID");
        pnlInvoiceCard.add(lblPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 408, 430, 20));

        pnlMain.add(pnlInvoiceCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 460, 445));

        btnPrintPdf.setBackground(new java.awt.Color(0, 102, 204));
        btnPrintPdf.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnPrintPdf.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintPdf.setText("📄 Print / Export PDF Bill");
        btnPrintPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrintPdf.addActionListener(this::btnPrintPdfActionPerformed);
        pnlMain.add(btnPrintPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 545, 290, 38));

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("✕ Close");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(this::btnCloseActionPerformed);
        pnlMain.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 545, 155, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPdfActionPerformed
        exportPdfInvoice();
    }//GEN-LAST:event_btnPrintPdfActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * Generate & Save PDF invoice using iText
     */
    private void exportPdfInvoice() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Bill / Invoice Receipt as PDF");
        fileChooser.setSelectedFile(new File("Bill_" + invoiceNo + ".pdf"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Documents (*.pdf)", "pdf"));

        int choice = fileChooser.showSaveDialog(this);
        if (choice != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        if (!fileToSave.getName().toLowerCase().endsWith(".pdf")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".pdf");
        }

        Document document = new Document(PageSize.A6, 15, 15, 15, 15);
        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
            document.open();

            // Brand Header
            com.itextpdf.text.Font brandFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 15, new BaseColor(11, 19, 43));
            Paragraph brand = new Paragraph("GAMING CAFE", brandFont);
            brand.setAlignment(Element.ALIGN_CENTER);
            document.add(brand);

            com.itextpdf.text.Font subFont = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.GRAY);
            Paragraph sub = new Paragraph("High-End Gaming & Esports Zone\nTel: +94 77 123 4567\n-----------------------------------------------------", subFont);
            sub.setAlignment(Element.ALIGN_CENTER);
            document.add(sub);

            com.itextpdf.text.Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, new BaseColor(0, 153, 255));
            Paragraph receiptTitle = new Paragraph("OFFICIAL PAYMENT RECEIPT", titleFont);
            receiptTitle.setAlignment(Element.ALIGN_CENTER);
            receiptTitle.setSpacingAfter(6);
            document.add(receiptTitle);

            // Invoice details table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{45f, 55f});

            com.itextpdf.text.Font fLabel = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, BaseColor.DARK_GRAY);
            com.itextpdf.text.Font fValue = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.BLACK);
            com.itextpdf.text.Font fTotal = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, new BaseColor(0, 153, 51));

            addPdfRow(table, "Invoice No:", invoiceNo, fLabel, fValue);
            addPdfRow(table, "Session ID:", sessionId, fLabel, fValue);
            addPdfRow(table, "Date & Time:", invoiceDateStr, fLabel, fValue);
            addPdfRow(table, "Staff In-Charge:", staffName, fLabel, fValue);
            addPdfRow(table, "--------------------", "--------------------", fLabel, fValue);
            addPdfRow(table, "Customer:", customerName, fLabel, fValue);
            addPdfRow(table, "Phone:", customerPhone, fLabel, fValue);
            addPdfRow(table, "Station:", stationName, fLabel, fValue);
            addPdfRow(table, "Category:", category, fLabel, fValue);
            addPdfRow(table, "--------------------", "--------------------", fLabel, fValue);

            int hrs = durationMinutes / 60;
            int mins = durationMinutes % 60;
            addPdfRow(table, "Duration:", String.format("%d mins (%02dh %02dm)", durationMinutes, hrs, mins), fLabel, fValue);
            addPdfRow(table, "Hourly Rate:", "Rs. " + String.format("%.2f", hourlyRate), fLabel, fValue);
            addPdfRow(table, "Sub Total:", "Rs. " + String.format("%.2f", subTotal), fLabel, fValue);
            addPdfRow(table, "Discount:", "Rs. " + String.format("%.2f", discount), fLabel, fValue);
            addPdfRow(table, "TOTAL AMOUNT:", "Rs. " + String.format("%.2f", netTotal), fLabel, fTotal);
            addPdfRow(table, "Payment Method:", "CASH (PAID)", fLabel, fValue);

            document.add(table);

            Paragraph footer = new Paragraph("\nThank you for gaming with us!\nVisit again for high-speed esports excitement!", subFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();

            int openChoice = JOptionPane.showConfirmDialog(
                this,
                "PDF Bill Receipt saved successfully!\nLocation: " + fileToSave.getAbsolutePath() + "\n\nWould you like to open it now?",
                "Invoice Exported",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
            );

            if (openChoice == JOptionPane.YES_OPTION) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(fileToSave);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error generating PDF Bill: " + ex.getMessage(), "PDF Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (document.isOpen()) {
                document.close();
            }
        }
    }

    private void addPdfRow(PdfPTable table, String label, String value, com.itextpdf.text.Font fL, com.itextpdf.text.Font fV) {
        PdfPCell c1 = new PdfPCell(new Phrase(label, fL));
        c1.setBorder(0);
        c1.setPaddingBottom(3);
        PdfPCell c2 = new PdfPCell(new Phrase(value, fV));
        c2.setBorder(0);
        c2.setHorizontalAlignment(Element.ALIGN_RIGHT);
        c2.setPaddingBottom(3);
        table.addCell(c1);
        table.addCell(c2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrintPdf;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCafeTitle;
    private javax.swing.JLabel lblCategoryBadge;
    private javax.swing.JLabel lblCusName;
    private javax.swing.JLabel lblCusPhone;
    private javax.swing.JLabel lblCustomerTitle;
    private javax.swing.JLabel lblDateTitle;
    private javax.swing.JLabel lblDiscountL;
    private javax.swing.JLabel lblDiscountVal;
    private javax.swing.JLabel lblDurationL;
    private javax.swing.JLabel lblDurationVal;
    private javax.swing.JLabel lblInvNoTitle;
    private javax.swing.JLabel lblInvoiceDate;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblNetTotalL;
    private javax.swing.JLabel lblNetTotalVal;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblRateL;
    private javax.swing.JLabel lblRateVal;
    private javax.swing.JLabel lblReceiptSubtitle;
    private javax.swing.JLabel lblSessionId;
    private javax.swing.JLabel lblSessionIdTitle;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JLabel lblStaffTitle;
    private javax.swing.JLabel lblStationName;
    private javax.swing.JLabel lblStationTitle;
    private javax.swing.JLabel lblSubTotalL;
    private javax.swing.JLabel lblSubTotalVal;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlInvoiceCard;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTotalBox;
    // End of variables declaration//GEN-END:variables
}
