package gamingcafe;

import java.awt.Font;
import java.awt.Image;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

public class Dash extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dash.class.getName());

    boolean isSidebarOpen = false;
    User user;
    DBConnection db = new DBConnection();
    PreparedStatement pst;
    ResultSet rs;

    public Dash(User user) {
        initComponents();
        connerRoud();
        loadUserTable();
        tableStyle(tableUser, jScrollPane1);
        tableStyle(tablePc, jScrollPane2);
        
        this.user = user;

//        btnDash.setBorderPainted(false);
//        btnLive.setBorderPainted(false);
//        btnPc.setBorderPainted(false);
//        btnReports.setBorderPainted(false);
//        btnLogOut.setBorderPainted(false);
//        btnAdmin.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePnl = new javax.swing.JPanel();
        contentPnl = new javax.swing.JPanel();
        sidebarPnl = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnLive = new javax.swing.JButton();
        btnPc = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAcc = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHam = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        DateTime = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        holder = new javax.swing.JPanel();
        pnlDash = new javax.swing.JPanel();
        liveGrid = new javax.swing.JPanel();
        summery = new javax.swing.JPanel();
        details = new javax.swing.JPanel();
        pnlLive = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnlPc = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        pnlAdmin = new javax.swing.JPanel();
        adminLeft = new javax.swing.JPanel();
        UserEdite = new javax.swing.JPanel();
        pnlUTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        userEdit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtFullName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnClean = new javax.swing.JButton();
        pnlPcM = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePc = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        pnlHistory = new javax.swing.JPanel();
        adminRigh = new javax.swing.JPanel();
        adminRightCard = new javax.swing.JPanel();
        btnUserManage = new javax.swing.JButton();
        btnUserAdd = new javax.swing.JButton();
        btnPcManage = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnToRepair = new javax.swing.JButton();
        btnIncome = new javax.swing.JButton();
        pnlSet = new javax.swing.JPanel();
        pnlAcc = new javax.swing.JPanel();
        Settings = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        setting1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        framePnl.setMaximumSize(new java.awt.Dimension(1280, 720));
        framePnl.setMinimumSize(new java.awt.Dimension(1280, 720));
        framePnl.setLayout(new java.awt.BorderLayout());

        contentPnl.setLayout(new java.awt.BorderLayout());

        sidebarPnl.setBackground(new java.awt.Color(0, 204, 255));
        sidebarPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        sidebarPnl.setMaximumSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setMinimumSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setPreferredSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setRequestFocusEnabled(false);
        sidebarPnl.setLayout(new java.awt.BorderLayout());

        pnlButton.setBackground(new java.awt.Color(11, 19, 43));
        pnlButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 0, 20, 0));
        pnlButton.setMaximumSize(new java.awt.Dimension(145, 392));
        pnlButton.setMinimumSize(new java.awt.Dimension(145, 392));
        pnlButton.setPreferredSize(new java.awt.Dimension(145, 392));
        pnlButton.setLayout(new java.awt.GridLayout(8, 1, 5, 0));

        btnDash.setBackground(new java.awt.Color(11, 19, 43));
        btnDash.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dash.png"))); // NOI18N
        btnDash.setText("Dashboard");
        btnDash.setToolTipText("Dashboard");
        btnDash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDash.addActionListener(this::btnDashActionPerformed);
        pnlButton.add(btnDash);

        btnLive.setBackground(new java.awt.Color(11, 19, 43));
        btnLive.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnLive.setForeground(new java.awt.Color(255, 255, 255));
        btnLive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/live.png"))); // NOI18N
        btnLive.setText("Live");
        btnLive.setToolTipText("");
        btnLive.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnLive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLive.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLive.addActionListener(this::btnLiveActionPerformed);
        pnlButton.add(btnLive);

        btnPc.setBackground(new java.awt.Color(11, 19, 43));
        btnPc.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnPc.setForeground(new java.awt.Color(255, 255, 255));
        btnPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pc.png"))); // NOI18N
        btnPc.setText("Pc");
        btnPc.setToolTipText("");
        btnPc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPc.addActionListener(this::btnPcActionPerformed);
        pnlButton.add(btnPc);

        btnReports.setBackground(new java.awt.Color(11, 19, 43));
        btnReports.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reports.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.setToolTipText("");
        btnReports.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReports.addActionListener(this::btnReportsActionPerformed);
        pnlButton.add(btnReports);

        btnLogOut.setBackground(new java.awt.Color(153, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logOut.png"))); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.setToolTipText("");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlButton.add(btnLogOut);

        btnAdmin.setBackground(new java.awt.Color(11, 19, 43));
        btnAdmin.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setToolTipText("");
        btnAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin.addActionListener(this::btnAdminActionPerformed);
        pnlButton.add(btnAdmin);

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        pnlButton.add(jPanel1);

        btnAcc.setBackground(new java.awt.Color(11, 19, 43));
        btnAcc.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        btnAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting.png"))); // NOI18N
        btnAcc.setText("Settings");
        btnAcc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnAcc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAcc.addActionListener(this::btnAccActionPerformed);
        pnlButton.add(btnAcc);

        sidebarPnl.add(pnlButton, java.awt.BorderLayout.CENTER);

        contentPnl.add(sidebarPnl, java.awt.BorderLayout.LINE_START);

        main.setBackground(new java.awt.Color(11, 19, 43));
        main.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        Header.setMaximumSize(new java.awt.Dimension(1180, 60));
        Header.setMinimumSize(new java.awt.Dimension(1180, 60));
        Header.setName(""); // NOI18N
        Header.setPreferredSize(new java.awt.Dimension(1180, 60));
        Header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        btnHam.setBackground(new java.awt.Color(0, 51, 102));
        btnHam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ci--hamburger-md.png"))); // NOI18N
        btnHam.setBorder(null);
        btnHam.addActionListener(this::btnHamActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHam, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        Header.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setMaximumSize(new java.awt.Dimension(300, 60));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 60));

        DateTime.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        DateTime.setForeground(new java.awt.Color(255, 255, 255));
        DateTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DateTime.setText("dsfdghtrhtr");
        DateTime.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateTime)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Header.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        Header.add(jPanel6, java.awt.BorderLayout.CENTER);

        main.add(Header, java.awt.BorderLayout.PAGE_START);

        holder.setBackground(new java.awt.Color(11, 19, 43));
        holder.setLayout(new java.awt.CardLayout());

        pnlDash.setBackground(new java.awt.Color(11, 19, 43));

        liveGrid.setBackground(new java.awt.Color(11, 19, 43));
        liveGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        javax.swing.GroupLayout liveGridLayout = new javax.swing.GroupLayout(liveGrid);
        liveGrid.setLayout(liveGridLayout);
        liveGridLayout.setHorizontalGroup(
            liveGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        liveGridLayout.setVerticalGroup(
            liveGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        summery.setBackground(new java.awt.Color(11, 19, 43));
        summery.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));

        javax.swing.GroupLayout summeryLayout = new javax.swing.GroupLayout(summery);
        summery.setLayout(summeryLayout);
        summeryLayout.setHorizontalGroup(
            summeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        summeryLayout.setVerticalGroup(
            summeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        details.setBackground(new java.awt.Color(11, 19, 43));
        details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        javax.swing.GroupLayout detailsLayout = new javax.swing.GroupLayout(details);
        details.setLayout(detailsLayout);
        detailsLayout.setHorizontalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        detailsLayout.setVerticalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDashLayout = new javax.swing.GroupLayout(pnlDash);
        pnlDash.setLayout(pnlDashLayout);
        pnlDashLayout.setHorizontalGroup(
            pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(summery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDashLayout.createSequentialGroup()
                        .addComponent(liveGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDashLayout.setVerticalGroup(
            pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liveGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holder.add(pnlDash, "card7");

        pnlLive.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLiveLayout = new javax.swing.GroupLayout(pnlLive);
        pnlLive.setLayout(pnlLiveLayout);
        pnlLiveLayout.setHorizontalGroup(
            pnlLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLiveLayout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );
        pnlLiveLayout.setVerticalGroup(
            pnlLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLiveLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        holder.add(pnlLive, "card6");

        pnlPc.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout pnlPcLayout = new javax.swing.GroupLayout(pnlPc);
        pnlPc.setLayout(pnlPcLayout);
        pnlPcLayout.setHorizontalGroup(
            pnlPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        pnlPcLayout.setVerticalGroup(
            pnlPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        holder.add(pnlPc, "card5");

        pnlReports.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        holder.add(pnlReports, "card4");

        pnlAdmin.setLayout(new java.awt.BorderLayout());

        adminLeft.setBackground(new java.awt.Color(255, 255, 255));
        adminLeft.setLayout(new java.awt.CardLayout());

        UserEdite.setBackground(new java.awt.Color(255, 255, 255));

        pnlUTable.setBackground(new java.awt.Color(255, 255, 255));
        pnlUTable.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true), "Users", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Intel One Mono SemiBold", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        pnlUTable.setMaximumSize(new java.awt.Dimension(968, 354));
        pnlUTable.setMinimumSize(new java.awt.Dimension(968, 354));

        tableUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Emp ID", "Full Name", "User Name", "NIC", "Email", "Phone", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.setMaximumSize(new java.awt.Dimension(450, 80));
        tableUser.setMinimumSize(new java.awt.Dimension(450, 80));
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);

        javax.swing.GroupLayout pnlUTableLayout = new javax.swing.GroupLayout(pnlUTable);
        pnlUTable.setLayout(pnlUTableLayout);
        pnlUTableLayout.setHorizontalGroup(
            pnlUTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUTableLayout.setVerticalGroup(
            pnlUTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        userEdit.setBackground(new java.awt.Color(255, 255, 255));
        userEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)), "Edite Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Emp No");

        txtUserNo.setEditable(false);
        txtUserNo.setBackground(new java.awt.Color(255, 255, 255));
        txtUserNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Full Name");

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("This action will reset users user name & password !");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("User Name");

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 102));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton1.setText("Reset Username & Password");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        txtFullName.setEditable(false);
        txtFullName.setBackground(new java.awt.Color(255, 255, 255));
        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUserName.setEditable(false);
        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Role");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        cmbRole.setToolTipText("");

        jButton6.setBackground(new java.awt.Color(0, 204, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Update User");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("This action will detactivate this user!");

        jToggleButton2.setBackground(new java.awt.Color(153, 153, 255));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton2.setText("Deactivate User");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        btnClean.setBackground(new java.awt.Color(0, 153, 153));
        btnClean.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clean.png"))); // NOI18N
        btnClean.setText("[F5]");
        btnClean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        javax.swing.GroupLayout userEditLayout = new javax.swing.GroupLayout(userEdit);
        userEdit.setLayout(userEditLayout);
        userEditLayout.setHorizontalGroup(
            userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userEditLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(userEditLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtUserNo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGroup(userEditLayout.createSequentialGroup()
                            .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFullName)
                                .addComponent(txtUserName))))
                    .addGroup(userEditLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userEditLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        userEditLayout.setVerticalGroup(
            userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userEditLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userEditLayout.createSequentialGroup()
                        .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userEditLayout.createSequentialGroup()
                                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(userEditLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtUserNo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(userEditLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userEditLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(userEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout UserEditeLayout = new javax.swing.GroupLayout(UserEdite);
        UserEdite.setLayout(UserEditeLayout);
        UserEditeLayout.setHorizontalGroup(
            UserEditeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserEditeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserEditeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        UserEditeLayout.setVerticalGroup(
            UserEditeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserEditeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        adminLeft.add(UserEdite, "card4");

        pnlPcM.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)), "Pc's", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        tablePc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PC ID", "Name", "Category", "Hourly Rate", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)), "Change Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(0, 102, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("PC ID");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 136, 40));
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 40));

        jLabel8.setText("Category");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, 40));

        jLabel9.setText("PC Name");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 136, 40));
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 40));

        jButton1.setText("Delete Data");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 127, 41));

        jButton2.setText("Update PC");
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 120, 41));

        jLabel14.setText("IP Address");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 136, 40));
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 190, 40));

        jLabel15.setText("Hourly Rate");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 136, 40));
        jPanel7.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 40));

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add PC");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 127, 41));

        jButton4.setText("Clear Feilds");
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 127, 41));

        jCheckBox2.setText("Block IP address");
        jPanel7.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel10.setText("CPU");

        jLabel11.setText("MotherBoard");

        jLabel12.setText("Ram Capasity");

        jLabel13.setText("VGA card");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 440, 210));

        javax.swing.GroupLayout pnlPcMLayout = new javax.swing.GroupLayout(pnlPcM);
        pnlPcM.setLayout(pnlPcMLayout);
        pnlPcMLayout.setHorizontalGroup(
            pnlPcMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPcMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPcMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPcMLayout.setVerticalGroup(
            pnlPcMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPcMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminLeft.add(pnlPcM, "card3");

        pnlHistory.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        adminLeft.add(pnlHistory, "card2");

        pnlAdmin.add(adminLeft, java.awt.BorderLayout.CENTER);

        adminRigh.setBackground(new java.awt.Color(0, 153, 255));
        adminRigh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        adminRigh.setMaximumSize(new java.awt.Dimension(160, 660));
        adminRigh.setMinimumSize(new java.awt.Dimension(160, 660));
        adminRigh.setPreferredSize(new java.awt.Dimension(160, 660));
        adminRigh.setLayout(new java.awt.CardLayout());

        adminRightCard.setBackground(new java.awt.Color(11, 19, 43));
        adminRightCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 0, 0, 0));
        adminRightCard.setMaximumSize(new java.awt.Dimension(155, 392));
        adminRightCard.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        btnUserManage.setBackground(new java.awt.Color(11, 19, 43));
        btnUserManage.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnUserManage.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icons/userManege.png"))); // NOI18N
        btnUserManage.setText("User Mange");
        btnUserManage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 14));
        btnUserManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserManage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUserManage.addActionListener(this::btnUserManageActionPerformed);
        adminRightCard.add(btnUserManage);

        btnUserAdd.setBackground(new java.awt.Color(0, 51, 153));
        btnUserAdd.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnUserAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnUserAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user Add.png"))); // NOI18N
        btnUserAdd.setText("Add User");
        btnUserAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnUserAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUserAdd.addActionListener(this::btnUserAddActionPerformed);
        adminRightCard.add(btnUserAdd);

        btnPcManage.setBackground(new java.awt.Color(11, 19, 43));
        btnPcManage.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnPcManage.setForeground(new java.awt.Color(255, 255, 255));
        btnPcManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icons/pcMange.png"))); // NOI18N
        btnPcManage.setText("Pc Manage");
        btnPcManage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 14));
        btnPcManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPcManage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPcManage.addActionListener(this::btnPcManageActionPerformed);
        adminRightCard.add(btnPcManage);

        btnHistory.setBackground(new java.awt.Color(11, 19, 43));
        btnHistory.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icons/history.png"))); // NOI18N
        btnHistory.setText("History");
        btnHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 14, 0, 0));
        btnHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        adminRightCard.add(btnHistory);

        btnToRepair.setBackground(new java.awt.Color(11, 19, 43));
        btnToRepair.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnToRepair.setForeground(new java.awt.Color(255, 255, 255));
        btnToRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icons/repair.png"))); // NOI18N
        btnToRepair.setText("To Repair");
        btnToRepair.setToolTipText("");
        btnToRepair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnToRepair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminRightCard.add(btnToRepair);

        btnIncome.setBackground(new java.awt.Color(11, 19, 43));
        btnIncome.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnIncome.setForeground(new java.awt.Color(255, 255, 255));
        btnIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icons/income.png"))); // NOI18N
        btnIncome.setText("Income");
        btnIncome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 14, 1, 1));
        btnIncome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminRightCard.add(btnIncome);

        adminRigh.add(adminRightCard, "card2");

        pnlAdmin.add(adminRigh, java.awt.BorderLayout.LINE_END);

        holder.add(pnlAdmin, "card3");

        pnlSet.setBackground(new java.awt.Color(11, 19, 43));
        pnlSet.setLayout(new java.awt.BorderLayout());

        pnlAcc.setBackground(new java.awt.Color(11, 19, 43));
        pnlAcc.setMaximumSize(new java.awt.Dimension(700, 660));
        pnlAcc.setMinimumSize(new java.awt.Dimension(700, 660));
        pnlAcc.setPreferredSize(new java.awt.Dimension(700, 660));

        javax.swing.GroupLayout pnlAccLayout = new javax.swing.GroupLayout(pnlAcc);
        pnlAcc.setLayout(pnlAccLayout);
        pnlAccLayout.setHorizontalGroup(
            pnlAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnlAccLayout.setVerticalGroup(
            pnlAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        pnlSet.add(pnlAcc, java.awt.BorderLayout.LINE_START);

        Settings.setBackground(new java.awt.Color(0, 153, 255));
        Settings.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        Settings.setLayout(new java.awt.CardLayout());

        jPanel10.setBackground(new java.awt.Color(11, 19, 43));

        setting1.setBackground(new java.awt.Color(11, 19, 43));
        setting1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Intel One Mono SemiBold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Intel One Mono SemiBold", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Toggle Button off");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        javax.swing.GroupLayout setting1Layout = new javax.swing.GroupLayout(setting1);
        setting1.setLayout(setting1Layout);
        setting1Layout.setHorizontalGroup(
            setting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setting1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        setting1Layout.setVerticalGroup(
            setting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setting1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jCheckBox1)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setting1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setting1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Settings.add(jPanel10, "card2");

        pnlSet.add(Settings, java.awt.BorderLayout.CENTER);

        holder.add(pnlSet, "card7");

        main.add(holder, java.awt.BorderLayout.CENTER);

        contentPnl.add(main, java.awt.BorderLayout.CENTER);

        framePnl.add(contentPnl, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        pnlDash.setVisible(true);
        pnlLive.setVisible(false);
        pnlPc.setVisible(false);
        pnlReports.setVisible(false);
        pnlAdmin.setVisible(false);
        pnlSet.setVisible(false);

    }//GEN-LAST:event_btnDashActionPerformed

    private void btnLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiveActionPerformed
        pnlLive.setVisible(true);
        pnlDash.setVisible(false);
        pnlPc.setVisible(false);
        pnlReports.setVisible(false);
        pnlAdmin.setVisible(false);
        pnlSet.setVisible(false);
    }//GEN-LAST:event_btnLiveActionPerformed

    private void btnPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPcActionPerformed
        pnlPc.setVisible(true);
        pnlDash.setVisible(false);
        pnlLive.setVisible(false);
        pnlReports.setVisible(false);
        pnlAdmin.setVisible(false);
        pnlSet.setVisible(false);
    }//GEN-LAST:event_btnPcActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        pnlPc.setVisible(false);
        pnlDash.setVisible(false);
        pnlLive.setVisible(false);
        pnlReports.setVisible(true);
        pnlAdmin.setVisible(false);
        pnlSet.setVisible(false);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        pnlPc.setVisible(false);
        pnlDash.setVisible(false);
        pnlLive.setVisible(false);
        pnlReports.setVisible(false);
        pnlSet.setVisible(false);
        pnlAdmin.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamActionPerformed
        Thread th = new Thread() {
            @Override
            public void run() {
                try {

                    if (isSidebarOpen) {
                        btnDash.setText("");
                        btnReports.setText("");
                        btnLive.setText("");
                        btnPc.setText("");
                        btnAdmin.setText("");
                        btnLogOut.setText("");
                        btnAcc.setText("");

                        for (int i = 145; i >= 60; i -= 10) {
                            Thread.sleep(15);
                            sidebarPnl.setPreferredSize(new java.awt.Dimension(i, sidebarPnl.getHeight()));
                            javax.swing.SwingUtilities.updateComponentTreeUI(sidebarPnl);
                        }
                        isSidebarOpen = false;

                    } else {

                        for (int i = 60; i <= 145; i += 10) {
                            Thread.sleep(15);
                            sidebarPnl.setPreferredSize(new java.awt.Dimension(i, sidebarPnl.getHeight()));
                            javax.swing.SwingUtilities.updateComponentTreeUI(sidebarPnl);

                            btnDash.setText("Dashboard");
                            btnReports.setText("Reports");
                            btnLive.setText("Live");
                            btnPc.setText("Pc");
                            btnAdmin.setText("Admin");
                            btnLogOut.setText("LogOut");
                            btnAcc.setText("Settings");

                        }
                        isSidebarOpen = true;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        th.start();
    }//GEN-LAST:event_btnHamActionPerformed

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
        pnlPc.setVisible(false);
        pnlDash.setVisible(false);
        pnlLive.setVisible(false);
        pnlReports.setVisible(false);
        pnlAdmin.setVisible(false);
        pnlSet.setVisible(true);
    }//GEN-LAST:event_btnAccActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAddActionPerformed
        UserReg reg = new UserReg();
        reg.setVisible(true);
    }//GEN-LAST:event_btnUserAddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        if (evt.getClickCount() == 2) {
            int selectedRow = tableUser.getSelectedRow();
            if (selectedRow != -1) {
                String selectUID = tableUser.getValueAt(selectedRow, 0).toString();
                try {
                    pst = db.con.prepareStatement("SELECT * FROM user WHERE emp_no = ?");
                    pst.setString(1, selectUID);
                    rs = pst.executeQuery();
                    
                    if(rs.next()){
                        txtUserNo.setText(rs.getString("emp_no"));
                        txtFullName.setText(rs.getString("f_name")+ " " + rs.getString("l_name"));
                        txtUserName.setText(rs.getString("username"));
                        cmbRole.setSelectedItem(rs.getString("role"));
                        
                        //image load 
                        byte[] imgByte = rs.getBytes("image");
                        if(imgByte != null){
                            ImageIcon img = new ImageIcon(imgByte);
                            Image scalledImage = img.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                            lblImage.setIcon(new ImageIcon(scalledImage));
                            
                        }else{
                            lblImage.setIcon(null);
                            lblImage.setText("No Iamge set yet...");
                        }
                        
                        
                    }
                } catch (SQLException ex) {
                    System.getLogger(Dash.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        }
    }//GEN-LAST:event_tableUserMouseClicked

    private void btnPcManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPcManageActionPerformed
        UserEdite.setVisible(false);
        pnlPcM.setVisible(true);
        pnlHistory.setVisible(false);
    }//GEN-LAST:event_btnPcManageActionPerformed

    private void btnUserManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManageActionPerformed
        UserEdite.setVisible(true);
        pnlPcM.setVisible(false);
        pnlHistory.setVisible(false);
    }//GEN-LAST:event_btnUserManageActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        UserEdite.setVisible(false);
        pnlPcM.setVisible(false);
        pnlHistory.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dash(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTime;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel UserEdite;
    private javax.swing.JPanel adminLeft;
    private javax.swing.JPanel adminRigh;
    private javax.swing.JPanel adminRightCard;
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnHam;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnIncome;
    private javax.swing.JButton btnLive;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPc;
    private javax.swing.JButton btnPcManage;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnToRepair;
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserManage;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JPanel contentPnl;
    private javax.swing.JPanel details;
    private javax.swing.JPanel framePnl;
    private javax.swing.JPanel holder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel liveGrid;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlAcc;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlLive;
    private javax.swing.JPanel pnlPc;
    private javax.swing.JPanel pnlPcM;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlSet;
    private javax.swing.JPanel pnlUTable;
    private javax.swing.JPanel setting1;
    private javax.swing.JPanel sidebarPnl;
    private javax.swing.JPanel summery;
    private javax.swing.JTable tablePc;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserNo;
    private javax.swing.JPanel userEdit;
    // End of variables declaration//GEN-END:variables

    private void connerRoud() {
        setting1.putClientProperty("FlatLaf.style", "arc: 20");
    }

    private void tableStyle(JTable table, JScrollPane scrollPane) {
        // 1. Table Main Colors
        table.setBackground(java.awt.Color.decode("#162244"));
        table.setForeground(java.awt.Color.WHITE);
        table.setSelectionBackground(java.awt.Color.decode("#0466c8")); // Active row color
        table.setSelectionForeground(java.awt.Color.WHITE);

        // 2. Grid & Layout
        table.setRowHeight(35);
        table.setShowVerticalLines(false);
        table.setGridColor(java.awt.Color.decode("#2A3B69"));

        // 3. Table Header
        javax.swing.table.JTableHeader header = table.getTableHeader();
        header.setBackground(java.awt.Color.decode("#0B132B"));
        header.setForeground(java.awt.Color.WHITE);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.decode("#0466c8")));

        // 4. ScrollPane
        if (scrollPane != null) {
            scrollPane.setBackground(java.awt.Color.decode("#162244"));
            scrollPane.getViewport().setBackground(java.awt.Color.decode("#162244"));
            scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        table.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        // 6. Text Alignment
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Table columns 
        for (int i = 0; i < table.getColumnModel().getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

    }

    private void loadUserTable() {

        try {
            DefaultTableModel dt = (DefaultTableModel) tableUser.getModel();
            dt.setRowCount(0);

            pst = db.con.prepareStatement("SELECT emp_no, f_name, l_name, nic, username, email, phone, role FROM user");
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString("emp_no"));
                v.add(rs.getString("f_name") + " " + rs.getString("l_name"));
                v.add(rs.getString("username"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("email"));
                v.add(rs.getString("phone"));
                v.add(rs.getString("role"));

                dt.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Table load error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
