package gamingcafe;

public class Dash extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dash.class.getName());

    boolean isSidebarOpen = false;

    public Dash(User user) {
        initComponents();
        
        btnDash.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePnl = new javax.swing.JPanel();
        contentPnl = new javax.swing.JPanel();
        sidebarPnl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnLive = new javax.swing.JButton();
        btnPc = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hamburger = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        framePnl.setMaximumSize(new java.awt.Dimension(1280, 720));
        framePnl.setMinimumSize(new java.awt.Dimension(1280, 720));
        framePnl.setLayout(new java.awt.BorderLayout());

        contentPnl.setLayout(new java.awt.BorderLayout());

        sidebarPnl.setBackground(new java.awt.Color(0, 204, 255));
        sidebarPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        sidebarPnl.setMaximumSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setMinimumSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setPreferredSize(new java.awt.Dimension(140, 720));
        sidebarPnl.setRequestFocusEnabled(false);
        sidebarPnl.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(11, 19, 43));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 0, 100, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(145, 392));
        jPanel3.setMinimumSize(new java.awt.Dimension(145, 392));
        jPanel3.setPreferredSize(new java.awt.Dimension(145, 392));
        jPanel3.setLayout(new java.awt.GridLayout(8, 1, 5, 0));

        btnDash.setBackground(new java.awt.Color(11, 19, 43));
        btnDash.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dash.png"))); // NOI18N
        btnDash.setText("Dashboard");
        btnDash.setToolTipText("Dashboard");
        btnDash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnDash);

        btnLive.setBackground(new java.awt.Color(11, 19, 43));
        btnLive.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLive.setForeground(new java.awt.Color(255, 255, 255));
        btnLive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/live.png"))); // NOI18N
        btnLive.setText("Live ");
        btnLive.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnLive.setContentAreaFilled(false);
        btnLive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLive.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnLive);

        btnPc.setBackground(new java.awt.Color(11, 19, 43));
        btnPc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPc.setForeground(new java.awt.Color(255, 255, 255));
        btnPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pc.png"))); // NOI18N
        btnPc.setText("Pc");
        btnPc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnPc.setContentAreaFilled(false);
        btnPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnPc);

        btnReports.setBackground(new java.awt.Color(11, 19, 43));
        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reports.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnReports.setContentAreaFilled(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnReports);

        btnLogOut.setBackground(new java.awt.Color(11, 19, 43));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logOut.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnLogOut);

        btnAdmin.setBackground(new java.awt.Color(11, 19, 43));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btnAdmin);

        sidebarPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        contentPnl.add(sidebarPnl, java.awt.BorderLayout.LINE_START);

        main.setBackground(new java.awt.Color(11, 19, 43));
        main.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1180, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(1180, 60));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 60));

        hamburger.setBackground(new java.awt.Color(0, 51, 102));
        hamburger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hamburger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ci--hamburger-md.png"))); // NOI18N
        hamburger.setBorder(null);
        hamburger.addActionListener(this::hamburgerActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hamburger)
                .addContainerGap(1142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(hamburger)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        main.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        main.add(jPanel2, java.awt.BorderLayout.CENTER);

        contentPnl.add(main, java.awt.BorderLayout.CENTER);

        framePnl.add(contentPnl, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgerActionPerformed

        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    if (isSidebarOpen) { 
                        
                        
                        for (int i = 145; i >= 70; i -= 10) {
                            Thread.sleep(15);
                            btnDash.setText("");
                            btnLive.setText("");
                            btnPc.setText("");
                            btnReports.setText("");
                            btnLogOut.setText("");
                            btnAdmin.setText("");
                            
                            sidebarPnl.setPreferredSize(new java.awt.Dimension(i, sidebarPnl.getHeight()));
                            javax.swing.SwingUtilities.updateComponentTreeUI(sidebarPnl);  
                        }
                        isSidebarOpen = false;

                    } else {
                        for (int i = 70; i <= 145; i += 10) {
                            Thread.sleep(15);
                            sidebarPnl.setPreferredSize(new java.awt.Dimension(i, sidebarPnl.getHeight()));
                            javax.swing.SwingUtilities.updateComponentTreeUI(sidebarPnl);  
                            
                            btnDash.setText("Dashobord");
                        }
                       
                        isSidebarOpen = true;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        th.start();
    }//GEN-LAST:event_hamburgerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dash(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnLive;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPc;
    private javax.swing.JButton btnReports;
    private javax.swing.JPanel contentPnl;
    private javax.swing.JPanel framePnl;
    private javax.swing.JButton hamburger;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel main;
    private javax.swing.JPanel sidebarPnl;
    // End of variables declaration//GEN-END:variables
}
